version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: skillex_assignment_mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - skillex_assignment_network

networks:
  skillex_assignment_network:

volumes:
  mysql_data:
